name: go

on: push

jobs:
  go:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.17.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run CI test
        run: make ci-test
